services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: filmak
      POSTGRES_PASSWORD: filmakpass
      POSTGRES_DB: filmakdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      PORT: 5000
      LOG_DIR: logs
      DATABASE_URL: postgres://filmak:filmakpass@db:5432/filmakdb
    depends_on:
      - db
    volumes:
      - ./backend/logs:/app/logs
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
