services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: filmak
      POSTGRES_PASSWORD: filmakpass
      POSTGRES_DB: filmakdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "filmak", "-d", "filmakdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 5000
      DATABASE_URL: postgres://filmak:filmakpass@db:5432/filmakdb
      JWT_SECRET: your_jwt_secret_here
      PGDATABASE: filmakdb
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  db_data:
